/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.kinitrojavatech.geco.gui;

import es.kinitrojavatech.geco.xml.Category;
import es.kinitrojavatech.geco.xml.Site;

/**
 *
 * @author quique
 */
public class JPanelCategory extends javax.swing.JPanel {

	/**
	 * Creates new form JPanelSites
	 */
	public JPanelCategory(final Category category) {
		initComponents();
		addEmptySite(category);
		for (final Site site : category.getSite()) {
			addSite(category, site);
		}
	}

	public void addSite(final Category category, final Site site) {
		final JPanelSite panelPassword = new JPanelSite(this, category, site);
		jTabbedPane1.add(panelPassword.getSiteName(), panelPassword);
		jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);
	}

	private void addEmptySite(final Category category) {
		final JPanelSite panelPassword = new JPanelSite(this, category, new Site());
		jTabbedPane1.add("Nuevo Site", panelPassword);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();

		jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(130, 130, 130)
						.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
						.addGap(170, 170, 170)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(98, 98, 98)
						.addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
						.addGap(102, 102, 102)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

}
