/*
 * Copyright (C) 2016 Kínitro JavaTech
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package es.kinitrojavatech.geco.gui;

import es.kinitrojavatech.geco.xml.EncryptedVolumes;
import es.kinitrojavatech.geco.xml.Volume;

/**
 *
 * @author quique
 */
public class JPanelEncFsCollection extends javax.swing.JPanel {

	private EncryptedVolumes volumes = null;

	/**
	 * Creates new form JPanelEncFs
	 */
	public JPanelEncFsCollection() {
		initComponents();
		initVolumesPanels();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();

		jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
		add(jTabbedPane1);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

	public void init(final EncryptedVolumes volumes) {
		this.volumes = volumes;
		jTabbedPane1.removeAll();
		initVolumesPanels();
	}

	private void initVolumesPanels() {
		JPanelEncFsVolume jPanel = new JPanelEncFsVolume(new Volume());
		jTabbedPane1.add("Nuevo FS", jPanel);
		if (volumes != null) {
			for (final Volume volume : volumes.getVolume()) {
				jPanel = new JPanelEncFsVolume(volume);
				jTabbedPane1.add("Nuevo FS", jPanel);
			}
		}
	}
}
