/*
 * Copyright (C) 2016 Kínitro JavaTech
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package es.kinitrojavatech.geco.gui;

import java.util.List;

import javax.swing.ImageIcon;

import es.kinitrojavatech.geco.desktop.DesktopIntegration;
import es.kinitrojavatech.geco.xml.EncryptedVolumes;
import es.kinitrojavatech.geco.xml.Volume;

/**
 *
 * @author quique
 */
public class JPanelEncFsCollection extends javax.swing.JPanel {

	private EncryptedVolumes volumes = null;

	/**
	 * Creates new form JPanelEncFs
	 */
	public JPanelEncFsCollection() {
		initComponents();
		initVolumesPanels();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();

		setLayout(new java.awt.BorderLayout());

		jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
		add(jTabbedPane1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTabbedPane jTabbedPane1;
	// End of variables declaration//GEN-END:variables

	public void init(final EncryptedVolumes volumes) {
		this.volumes = volumes;
		jTabbedPane1.removeAll();
		initVolumesPanels();
	}

	private void initVolumesPanels() {
		JPanelEncFsVolume jPanel = new JPanelEncFsVolume(this, volumes, new Volume(), false);
		jTabbedPane1.add("Nuevo FS", jPanel);
		if (volumes != null) {
			final List<String> mountedEncFs = DesktopIntegration.getDesktop().mountedEncFs();
			for (final Volume volume : volumes.getVolume()) {
				final boolean mounted = mountedEncFs.contains(volume.getMountPoint());
				jPanel = new JPanelEncFsVolume(this, volumes, volume, mounted);
				jTabbedPane1.add(volume.getName(), jPanel);
				changeStatus(jPanel, mounted);
			}
		}
	}

	public void addVolume(final Volume volume) {
		final List<String> mountedEncFs = DesktopIntegration.getDesktop().mountedEncFs();
		final boolean mounted = mountedEncFs.contains(volume.getMountPoint());
		final JPanelEncFsVolume panelEncFsVolume = new JPanelEncFsVolume(this, volumes, volume, mounted);
		jTabbedPane1.add(volume.getName(), panelEncFsVolume);
		jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);
	}

	public void changeStatus(final JPanelEncFsVolume panel, final boolean mounted) {
		final int index = jTabbedPane1.indexOfComponent(panel);
		if (index > -1) {
			if (mounted) {
				final ImageIcon icon = new ImageIcon(
						getClass().getResource("/es/kinitrojavatech/geco/gui/icons/ok16.png"));
				jTabbedPane1.setIconAt(index, icon);
			} else {
				jTabbedPane1.setIconAt(index, null);
			}
		}
	}
}
